services:
  api:
    image: rwtproj-api
    build:
      context: ./RWTapi
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    ports:
      - "8080:8080"
    env_file:
      - ./RWTapi/config/.env
    volumes:
      - ./RWTapi/images:/app/images
      - ./RWTapi/music:/app/music
    depends_on:
      - db
    networks:
      - rwt-network

  frontend:
    image: rwtproj-frontend
    build:
      context: ./rwt
      dockerfile: Dockerfile  # Updated to match your React Dockerfile name
    platform: linux/arm64/v8
    ports:
      - "3000:80"
    networks:
      - rwt-network

  db:
    image: mysql:8.0
    platform: linux/arm64/v8  # Changed to match other services
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rwtchoir
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./rwtchoir.sql:/docker-entrypoint-initdb.d/rwtchoir.sql
    networks:
      - rwt-network

networks:
  rwt-network:

volumes:
  db-data: