version: '3.8'

services:
  api:
    build:
      context: ./RWTapi
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rwtchoir
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_HOST=db  # Use the service name 'db' as the hostname
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - ENCRYPT_KEY=e5d9c4e2a3e0b1a8
    depends_on:
      - db

  frontend:
    build:
      context: ./rwt
      dockerfile: rwtReact.dockerfile  # Ensure this file exists in the rwt directory
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 in the container

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rwtchoir
    volumes:
      - db-data:/var/lib/mysql

networks:
  rwt-network:

volumes:
  db-data: