services:
  api:
    image: rwtproj-api
    platform: linux/arm64/v8
    ports:
      - "8080:8080"
    env_file:
      - /root/RWTProj/RWTapi/config/api.env
    volumes:
      - /root/RWTProj/images:/app/images
      - /root/RWTProj/music:/app/music
    depends_on:
      - db
    networks:
      - rwt-network

  frontend:
    image: rwtproj-frontend
    platform: linux/arm64/v8
    ports:
      - "3000:3000"  # Changed from "3000:80" to "3000:3000"
    env_file:
      - /root/RWTProj/rwt/config/frontend.env
    networks:
      - rwt-network

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rwtchoir
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - /root/RWTProj/rwtchoir.sql:/docker-entrypoint-initdb.d/rwtchoir.sql
    networks:
      - rwt-network

networks:
  rwt-network:

volumes:
  db-data: